platform :ios, '8.0'
use_frameworks!

target 'VKDocReader' do
  pod 'SwiftyJSON', '~> 2.3.2'
  pod 'SSKeychain', '~> 1.3.1'
  pod 'Alamofire', '~> 3.2.1'
#  pod 'RealmSwift'
#  pod 'ViewDeck', '~> 2.4.1'
end
